CREATE DATABASE IF NOT EXISTS takeHomeDb;
USE takeHomeDb;

CREATE TABLE users IF NOT EXISTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100)  NOT NULL,
  user_name VARCHAR(100) UNIQUE NOT NULL,
  date_of_birth DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
